language: python
python:
    - "3.6"
services:
  - postgresql

env:
  global:
    - APP_SETTINGS="testing"
    - DATABASE_URL='postgresql://postgres:Kp15712Kp@localhost/test_db'

install:
    - pip install -r requirements.txt

before_script:
  - "psql -c 'create database test_db;' -U postgres"
#   - python manage.py db init
#   - python manage.py db migrate
  - python manage.py db upgrade

script:
    - coverage run --source=app/ -m pytest
    - coverage report
    
after_success:
    - coveralls